//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FacebookEntities : DbContext
    {
        public FacebookEntities()
            : base("name=FacebookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DailyPosts> DailyPosts { get; set; }
        public DbSet<PodyakaLog> PodyakaLog { get; set; }
        public DbSet<Podyaki> Podyaki { get; set; }
        public DbSet<Posts> Posts { get; set; }
        public DbSet<Promote> Promote { get; set; }
        public DbSet<ServiseData> ServiseData { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Vote> Vote { get; set; }
        public DbSet<Votings> Votings { get; set; }
        public DbSet<VotingVariants> VotingVariants { get; set; }
        public DbSet<AdministationPodyakas> AdministationPodyakas { get; set; }
        public DbSet<UserFriends> UserFriends { get; set; }
    
        public virtual ObjectResult<Nullable<long>> GetAvtoritetRank(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("GetAvtoritetRank", userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> GetVoteRank(Nullable<int> voteVariantId, Nullable<int> votingId)
        {
            var voteVariantIdParameter = voteVariantId.HasValue ?
                new ObjectParameter("VoteVariantId", voteVariantId) :
                new ObjectParameter("VoteVariantId", typeof(int));
    
            var votingIdParameter = votingId.HasValue ?
                new ObjectParameter("VotingId", votingId) :
                new ObjectParameter("VotingId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("GetVoteRank", voteVariantIdParameter, votingIdParameter);
        }
    
        public virtual ObjectResult<GetUsersSortedByAvtoritet_Result> GetUsersSortedByAvtoritet(Nullable<int> count)
        {
            var countParameter = count.HasValue ?
                new ObjectParameter("Count", count) :
                new ObjectParameter("Count", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsersSortedByAvtoritet_Result>("GetUsersSortedByAvtoritet", countParameter);
        }
    
        public virtual int SetOurFriendUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetOurFriendUsers");
        }
    }
}
