//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public Posts()
        {
            this.DailyPosts = new HashSet<DailyPosts>();
            this.Podyaki = new HashSet<Podyaki>();
        }
    
        public string PostId { get; set; }
        public string UserId { get; set; }
        public int PodyakiCount { get; set; }
    
        public virtual ICollection<DailyPosts> DailyPosts { get; set; }
        public virtual ICollection<Podyaki> Podyaki { get; set; }
        public virtual Users Users { get; set; }
    }
}
