//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Podyaki = new HashSet<Podyaki>();
            this.Posts = new HashSet<Posts>();
            this.Promote = new HashSet<Promote>();
            this.Vote = new HashSet<Vote>();
            this.VotingVariants = new HashSet<VotingVariants>();
            this.AdministationPodyakas = new HashSet<AdministationPodyakas>();
            this.UserFriends = new HashSet<UserFriends>();
        }
    
        public string UserId { get; set; }
        public int PodyakiCount { get; set; }
        public double Avtoritet { get; set; }
        public bool IsInPeopleVouting { get; set; }
        public string Name { get; set; }
        public string PictureScr { get; set; }
        public System.DateTime LastActivity { get; set; }
        public string Link { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsVIP { get; set; }
    
        public virtual ICollection<Podyaki> Podyaki { get; set; }
        public virtual ICollection<Posts> Posts { get; set; }
        public virtual ICollection<Promote> Promote { get; set; }
        public virtual ICollection<Vote> Vote { get; set; }
        public virtual ICollection<VotingVariants> VotingVariants { get; set; }
        public virtual ICollection<AdministationPodyakas> AdministationPodyakas { get; set; }
        public virtual ICollection<UserFriends> UserFriends { get; set; }
    }
}
