//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Votings
    {
        public Votings()
        {
            this.VotingVariants = new HashSet<VotingVariants>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsPeople { get; set; }
        public bool IsClosed { get; set; }
    
        public virtual ICollection<VotingVariants> VotingVariants { get; set; }
    }
}
